# Numpy
- It is mainly used for numerical computing in python
- It has n-dimensional array which is much faster and more memory efficient

In [4]:
import numpy as np

In [6]:
arr1 = np.array([10,20,30])
arr2 = np.array([1,2,3])

# Element wise operation
sum_arr = arr1 + arr2
print("Sum of arrays:", sum_arr)

Sum of arrays: [11 22 33]


In [7]:
# Element wise multiplication
prod_arr = arr1 * 2
print("Product of array and scalar:", prod_arr)

Product of array and scalar: [20 40 60]


### Create an array of 10 zeros


In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Create an array of 10 ones

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Create an array of 10 fives

In [11]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

### Create an array of the integers from 10 to 50

In [12]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

### Create an array of all the even integers from 10 to 50

In [13]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

### Create a 3x3 matrix with values ranging from 0 to 8

In [15]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Numpy indexing and Slicing

In [16]:
mat = np.arange(1,26).reshape(5,5)

In [17]:
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [18]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [19]:
mat[3,4]

np.int64(20)

In [20]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [21]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [22]:
mat[4,:]

array([21, 22, 23, 24, 25])